#!/usr/bin/env node
// Project-wide audit of the mechanically checkable coding-standards rules, for the code-audit skill.
// Counts, not prose: the model reads a few dozen lines instead of opening files to look for violations.
//
//   node audit.js [path...] [--standard css,html,js,ts,a11y,seo,perf,git,version] [--rule ID] [--top N] [--limit N]
//                 [--context] [--baseline] [--ignore GLOB]... [--commits N] [--no-git] [--include-generated] [--skipped] [--json] [--list] [--cwd D]
//
// Findings are "rule" (a violation) or "review" (a heuristic candidate that needs judgement) or "info" (a count).
// Exit 0 normally; with a saved baseline (.claude/code-audit.baseline.json) exit 1 only when a count rose.
// Config (optional): <cwd>/.claude/code-audit.json
//   { "ignore": ["glob"...], "skipRules": ["id"...], "styleBlocks": "count|forbid", "commits": 200 }
// Also used by the edit-check engine (profile "edit": the small set of rules it has always run per edit).
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const CSS_EXT = /\.(css|scss|sass|less|pcss)$/i;
const MARKUP_EXT = /\.(html?|php|vue|svelte|astro|jsx|tsx|twig|liquid)$/i;
const PAGE_EXT = /\.(html?|astro)$/i;
const SCRIPT_EXT = /\.(js|jsx|mjs|cjs|ts|tsx|mts|cts)$/i;
const TS_EXT = /\.(ts|tsx|mts|cts)$/i;
const TOKEN_FILE = /(token|variable|theme|palette|colou?rs?)/i;
const EMAIL_FILE = /e-?mail|mailer|newsletter/i;
const SKIP_DIRS = /(^|\/)(node_modules|dist|build|vendor|coverage|\.[^/]+)\//; // dot-directories (.git, .claude, .next, .astro) are tooling
const GENERATED = /@generated|auto-?generated|do not edit|generated by|sourceMappingURL=/i;
const GENERATED_NAME = /\.(output|generated|bundle|chunk|min)\.|-min\./i;
const BASELINE = path.join('.claude', 'code-audit.baseline.json');

const norm = (p) => p.split(path.sep).join('/');
const blank = (m) => m.replace(/[^\n]/g, ' '); // keep newlines so line numbers survive
const run = (cmd, args, cwd, timeout = 20000) => spawnSync(cmd, args, { cwd, encoding: 'utf8', timeout, maxBuffer: 32 * 1024 * 1024 });
function lineFn(text) {
  const nl = [];
  for (let i = text.indexOf('\n'); i >= 0; i = text.indexOf('\n', i + 1)) nl.push(i);
  return (idx) => { let lo = 0, hi = nl.length; while (lo < hi) { const m = (lo + hi) >> 1; if (nl[m] < idx) lo = m + 1; else hi = m; } return lo + 1; };
}
function globRe(g) {
  const s = norm(g).replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*\*\//g, '\u0001').replace(/\*\*/g, '\u0002').replace(/\*/g, '[^/]*').replace(/\u0001/g, '(?:.*/)?').replace(/\u0002/g, '.*');
  return new RegExp('(^|/)' + s + '$');
}

// ---- rule table: the single place that says what exists ----
const R = (id, std, kind, what, edit = false) => [id, { id, std, kind, what, edit }];
const RULES = Object.fromEntries([
  R('css-04', 'css', 'rule', 'font-weight must be numeric', true),
  R('css-05', 'css', 'rule', 'line-height must be a --leading-* token'),
  R('css-06', 'css', 'rule', 'transition must name its properties (no "all", no single transition variable)'),
  R('css-10', 'css', 'rule', 'hardcoded colour, use a token', true),
  R('css-14', 'css', 'rule', '!important is banned', true),
  R('css-17', 'css', 'rule', 'min-width-only media query; use an isolated range (the 1400px top zone is exempt)'),
  R('css-style-block', 'css', 'info', '<style> block (allowed unless it holds JS-state CSS or the project forbids it)'),
  R('h-02', 'html', 'rule', 'inline style attribute', true),
  R('h-03', 'html', 'rule', 'id selector in CSS (ids are for behaviour, classes for styling)'),
  R('h-04', 'html', 'rule', '<img> has no alt attribute', true),
  R('h-05', 'html', 'rule', 'presentational attribute', true),
  R('h-08', 'html', 'rule', 'heading level skipped'),
  R('h-10', 'html', 'rule', 'banned tag in UI markup', true),
  R('a11y-03', 'a11y', 'rule', 'page must have exactly one <main>'),
  R('a11y-05', 'a11y', 'review', 'div/span with onclick and no role or tabindex'),
  R('a11y-06', 'a11y', 'review', 'outline removed; check a visible custom focus style exists'),
  R('seo-01', 'seo', 'rule', 'page has no <title>'),
  R('seo-02', 'seo', 'rule', 'page has no meta description'),
  R('seo-03', 'seo', 'rule', 'page must have exactly one <h1>'),
  R('seo-06', 'seo', 'rule', 'page has no canonical link'),
  R('seo-07', 'seo', 'rule', 'page has no og:title'),
  R('perf-02', 'perf', 'rule', '<img> has no width/height attributes'),
  R('perf-06', 'perf', 'rule', 'blocking <script src> in <head> (add defer, async or type=module)'),
  R('js-03', 'js', 'rule', 'console.log/warn/error in committed code'),
  R('js-04', 'js', 'review', 'addEventListener with no removeEventListener or abort signal in the file'),
  R('js-08', 'js', 'review', 'commented-out code'),
  R('js-09', 'js', 'rule', 'var is not permitted'),
  R('js-10', 'js', 'rule', 'use === and !==, never == or !='),
  R('js-11', 'js', 'rule', 'state attribute removed or set empty; update its value instead'),
  R('js-11-class', 'js', 'review', 'classList add/remove/toggle; state must not be a class'),
  R('ts-01', 'ts', 'rule', 'explicit any; use unknown and narrow'),
  R('ts-04', 'ts', 'rule', 'console.log/warn/error in committed code'),
  R('ts-05', 'ts', 'review', 'addEventListener with no removeEventListener or abort signal in the file'),
  R('ts-09', 'ts', 'review', 'commented-out code'),
  R('ts-10', 'ts', 'rule', 'var is not permitted'),
  R('ts-11', 'ts', 'rule', 'use === and !==, never == or !='),
  R('ts-12', 'ts', 'rule', 'object shape declared with type; use interface'),
  R('ts-13', 'ts', 'rule', 'enum name must be PascalCase'),
  R('ts-15', 'ts', 'review', 'type assertion (as) without a justifying comment'),
  R('ts-16', 'ts', 'rule', 'state attribute removed or set empty; update its value instead'),
  R('ts-16-class', 'ts', 'review', 'classList add/remove/toggle; state must not be a class'),
  R('g-05', 'git', 'rule', 'branch name is not [type]/[short-description]'),
  R('g-06', 'git', 'rule', 'commit message is not "[type]: [summary]" with a G-07 type'),
  R('g-08', 'git', 'rule', 'commit header over 50 characters, or summary ends with a period or is past tense'),
  R('v-05', 'version', 'review', 'package.json version differs from the latest git tag (fine if a bump is pending)'),
  R('v-08', 'version', 'rule', 'no CHANGELOG.md entry for the package.json version'),
  R('v-09', 'version', 'rule', 'pre-release suffix must be alpha.N, beta.N or rc.N'),
]);
const NOT_CHECKED = 'Not machine-checked, judge by reading: css 01-03, 07-09, 11-13, 15-16, 18-22 · h-01, h-06, h-07, h-09 · ts/js function size, state, async errors, import order · a11y 01-02, 04, 07-18 · seo 04-05, 08-12 · perf 01, 03-05, 07-15 · g-01..04, g-09..12 · v-01..04, v-06, v-07.';

// ---- text helpers ----
// Blank comments (and string contents unless keepStrings) while keeping every newline.
function stripCode(src, keepStrings = false) {
  let out = '';
  const n = src.length;
  let i = 0;
  while (i < n) {
    const c = src[i], d = src[i + 1];
    if (c === '/' && d === '/') { let j = src.indexOf('\n', i); if (j < 0) j = n; out += ' '.repeat(j - i); i = j; }
    else if (c === '/' && d === '*') { let j = src.indexOf('*/', i + 2); j = j < 0 ? n : j + 2; out += blank(src.slice(i, j)); i = j; }
    else if (c === '"' || c === "'" || c === '`') {
      let j = i + 1;
      while (j < n && src[j] !== c && (c === '`' || src[j] !== '\n')) { if (src[j] === '\\') j++; j++; }
      j = Math.min(j + 1, n);
      const s = src.slice(i, j);
      if (keepStrings) out += s;
      else { const closed = s.length > 1 && s[s.length - 1] === c; out += c + blank(closed ? s.slice(1, -1) : s.slice(1)) + (closed ? c : ''); }
      i = j;
    } else { out += c; i++; }
  }
  return out;
}
const blankHtmlComments = (t) => t.replace(/<!--[\s\S]*?-->/g, blank);
const preludeAt = (css, idx) => {
  const j = css.lastIndexOf('{', idx);
  if (j < 0) return '';
  const k = Math.max(css.lastIndexOf('}', j - 1), css.lastIndexOf(';', j - 1), css.lastIndexOf('{', j - 1));
  return css.slice(k + 1, j);
};
function matchBrace(s, open) { // index just after the brace that closes the one at `open`
  let depth = 0;
  for (let i = open; i < s.length; i++) { if (s[i] === '{') depth++; else if (s[i] === '}' && --depth === 0) return i + 1; }
  return s.length;
}

// JSX text (prose between tags) is not code. Only text inside an element counts (depth > 0), and {expressions}
// in it stay code. Outside any element, an opening '<' right after an identifier is a generic (useState<string>())
// or a comparison, not a tag; inside one, text may run straight into a tag (Hello</b>).
const JSX_TAG = /<(\/?)([A-Za-z][\w.:-]*)?((?:=>|>=|[^<>])*?)(\/?)>/g;
function blankJsxText(code) {
  const out = code.split('');
  let depth = 0;
  let last = 0;
  for (const m of code.matchAll(JSX_TAG)) {
    const [whole, close, name, attrs, self] = m;
    if (!name && (attrs.trim() || self)) continue; // only <> and </> are tags without a name
    if (!close && depth === 0 && /[\w$)\]]/.test(code[m.index - 1] || '')) continue;
    if (depth > 0) {
      let br = 0;
      for (let i = last; i < m.index; i++) {
        const c = code[i];
        if (c === '{') br++;
        else if (c === '}') { if (br > 0) br--; continue; }
        if (br === 0 && c !== '\n') out[i] = ' ';
      }
    }
    if (close) depth = Math.max(0, depth - 1);
    else if (!self) depth++;
    last = m.index + whole.length;
  }
  return out.join('');
}

// ---- file-level packs ----
function cssChecks(rel, text) {
  const out = [];
  const L = lineFn(text);
  const add = (line, rule, msg) => out.push({ file: rel, line, rule, msg });
  let css = text.replace(/\/\*[\s\S]*?\*\//g, blank);
  if (/\.(scss|sass|less)$/i.test(rel)) css = css.replace(/(^|[^:])(\/\/[^\n]*)/g, (m, p, c) => p + blank(c)); // line comments, not url(http://...)
  const tokenFile = TOKEN_FILE.test(path.basename(rel));
  css.split('\n').forEach((l, i) => {
    if (/!\s*important\b/i.test(l)) add(i + 1, 'css-14', '!important is banned');
    if (/\bfont-weight\s*:\s*(bold|bolder|lighter|normal|semi-?bold|medium|light)\b/i.test(l)) add(i + 1, 'css-04', 'font-weight must be numeric');
    // custom-property definitions (--x: #fff) are how tokens are declared, so they are not flagged here
    const noUrl = l.replace(/url\([^)]*\)/gi, '').replace(/--[\w-]+\s*:[^;}]*/g, '');
    if (!tokenFile && /#[0-9a-f]{3,8}\b|\b(rgba?|hsla?|oklch)\s*\(/i.test(noUrl)) add(i + 1, 'css-10', 'hardcoded colour, use a token');
  });
  const plain = css.replace(/(["'])(?:\\.|(?!\1)[^\\\n])*\1/g, blank).replace(/url\([^)]*\)/gi, blank);
  if (!tokenFile) {
    for (const m of plain.matchAll(/(?<![\w-])line-height\s*:\s*([^;}]+)/gi)) {
      const v = m[1].trim();
      if (!/^var\(\s*--(?:[a-z][a-z0-9]*-)?leading-/.test(v) && !/^(inherit|initial|unset|revert)\b/i.test(v)) add(L(m.index), 'css-05', 'line-height must be a --leading-* token');
    }
  }
  for (const m of plain.matchAll(/(?<![\w-])transition(?:-property)?\s*:\s*([^;}]+)/gi)) {
    const v = m[1].trim();
    if (/\ball\b/i.test(v) || /^var\(\s*--transition[\w-]*\s*\)$/i.test(v)) add(L(m.index), 'css-06', 'transition must name its properties');
  }
  for (const m of plain.matchAll(/@media([^{]*)\{/gi)) {
    for (const part of m[1].split(',')) {
      const min = /min-width\s*:\s*([\d.]+)px|width\s*>=?\s*([\d.]+)px/i.exec(part);
      const max = /max-width\s*:|width\s*<=?\s*[\d.]/i.test(part.replace(/min-width/gi, ''));
      if (min && !max && Number(min[1] || min[2]) !== 1400) add(L(m.index), 'css-17', 'min-width-only media query; use an isolated range');
    }
  }
  for (const m of plain.matchAll(/([^{};]+)\{/g)) {
    const pre = m[1];
    if (/^\s*@/.test(pre)) continue;
    const id = /#([A-Za-z_-][\w-]*)/.exec(pre);
    if (id) add(L(m.index + m[0].indexOf('#')), 'h-03', `id selector #${id[1]}`);
  }
  for (const m of plain.matchAll(/(?<![\w-])outline(?:-width)?\s*:\s*(none|0)\b/gi)) {
    if (!/:not\(\s*:focus-visible\s*\)|focus-inner/i.test(preludeAt(plain, m.index))) add(L(m.index), 'a11y-06', 'outline removed; check a visible custom focus style exists');
  }
  return out;
}

function markupChecks(rel, text) {
  const out = [];
  const L = lineFn(text);
  const add = (line, rule, msg) => out.push({ file: rel, line, rule, msg });
  const liquid = /\.liquid$/i.test(rel);
  let html = blankHtmlComments(text);
  if (liquid) html = html.replace(/\{%-?\s*comment\s*-?%\}[\s\S]*?\{%-?\s*endcomment\s*-?%\}|\{%-?\s*#[\s\S]*?-?%\}/g, blank);
  for (const m of html.matchAll(/<img\b[^>]*>/gis)) {
    const spread = /\{\s*\.\.\./.test(m[0]);
    if (!/\balt\s*=/i.test(m[0]) && !spread) add(L(m.index), 'h-04', '<img> has no alt attribute');
    if (!EMAIL_FILE.test(rel) && !spread && !(/\bwidth\s*=/i.test(m[0]) && /\bheight\s*=/i.test(m[0]))) add(L(m.index), 'perf-02', '<img> has no width/height attributes');
  }
  const styleProp = /\.(jsx|tsx)$/i.test(rel) && /@react-pdf\/renderer|react-native/.test(text); // there, style is the only styling API
  if (!styleProp) for (const m of html.matchAll(/\sstyle\s*=/gi)) add(L(m.index), 'h-02', 'inline style');
  for (const m of html.matchAll(/\s(align|valign|bgcolor)\s*=/gi)) add(L(m.index), 'h-05', `presentational attribute ${m[1].toLowerCase()}`);
  if (!EMAIL_FILE.test(rel)) for (const m of html.matchAll(/<(br|strong|small)\b/gi)) add(L(m.index), 'h-10', `<${m[1].toLowerCase()}> is banned in UI markup`);
  for (const m of html.matchAll(/<(div|span)\b[^>]*\bonclick\s*=[^>]*>/gis)) {
    if (!/\b(tabindex|role)\s*=/i.test(m[0])) add(L(m.index), 'a11y-05', `<${m[1].toLowerCase()}> with onclick and no role or tabindex`);
  }
  if (!/\.(jsx|tsx)$/i.test(rel) && !EMAIL_FILE.test(rel)) {
    for (const m of html.matchAll(/<style\b/gi)) add(L(m.index), 'css-style-block', '<style> block');
    if (liquid) for (const m of html.matchAll(/\{%-?\s*(style|stylesheet)\s*-?%\}/g)) add(L(m.index), 'css-style-block', `{% ${m[1]} %} block`);
  }
  return out;
}

// Whole-page rules: only for complete documents (a file that has its own <html>), so partials and layouts are not judged.
function pageChecks(rel, text) {
  const doc = blankHtmlComments(text);
  if (!/<html[\s>]/i.test(doc) || EMAIL_FILE.test(rel)) return [];
  const out = [];
  const L = lineFn(text);
  const add = (line, rule, msg) => out.push({ file: rel, line, rule, msg });
  const body = doc.replace(/(<(script|style)\b[^>]*>)([\s\S]*?)(<\/\2>)/gi, (m, a, _t, b, c) => a + blank(b) + c);
  if (!/<title[\s>]/i.test(body)) add(1, 'seo-01', 'page has no <title>');
  if (!/<meta\b[^>]*\bname\s*=\s*["']description["']/i.test(body)) add(1, 'seo-02', 'page has no meta description');
  if (!/<link\b[^>]*\brel\s*=\s*["']canonical["']/i.test(body)) add(1, 'seo-06', 'page has no canonical link');
  if (!/<meta\b[^>]*\bproperty\s*=\s*["']og:title["']/i.test(body)) add(1, 'seo-07', 'page has no og:title');
  if (/<slot\b/i.test(body)) return out; // a layout: pages fill the slot, so main, h1 and heading order belong to them
  const mains = [...body.matchAll(/<main\b/gi)];
  if (mains.length !== 1) add(mains[1] ? L(mains[1].index) : 1, 'a11y-03', `page has ${mains.length} <main> elements, needs exactly one`);
  const h1 = [...body.matchAll(/<h1\b/gi)];
  if (h1.length !== 1) add(h1[1] ? L(h1[1].index) : 1, 'seo-03', `page has ${h1.length} <h1> elements, needs exactly one`);
  let prev = 0;
  for (const m of body.matchAll(/<h([1-6])\b/gi)) {
    const lvl = Number(m[1]);
    if (lvl > prev + 1) add(L(m.index), 'h-08', `heading jumps from h${prev || 'none'} to h${lvl}`);
    prev = lvl;
  }
  const head = /<head\b[\s\S]*?<\/head>/i.exec(body);
  if (head) {
    for (const m of head[0].matchAll(/<script\b([^>]*)>/gi)) {
      if (/\bsrc\s*=/i.test(m[1]) && !/\b(defer|async)\b|type\s*=\s*["']module["']/i.test(m[1])) add(L(head.index + m.index), 'perf-06', 'blocking <script src> in <head>');
    }
  }
  return out;
}

function scriptChecks(rel, text) {
  const ts = TS_EXT.test(rel);
  const id = (jsId, tsId) => (ts ? tsId : jsId);
  const out = [];
  const L = lineFn(text);
  const add = (line, rule, msg) => out.push({ file: rel, line, rule, msg });
  const jsx = /\.(jsx|tsx)$/i.test(rel);
  const code = jsx ? blankJsxText(stripCode(text)) : stripCode(text); // comments, string contents and JSX prose blanked
  const withStrings = stripCode(text, true); // comments blanked only
  for (const m of code.matchAll(/\bconsole\s*\.\s*(log|warn|error)\s*\(/g)) add(L(m.index), id('js-03', 'ts-04'), `console.${m[1]} in committed code`);
  for (const m of code.matchAll(/(?<![\w$.])var\s+[\w${[]/g)) add(L(m.index), id('js-09', 'ts-10'), 'var is not permitted');
  for (const m of code.matchAll(/(?<![=!<>+\-*/%&|^])==(?!=)|!=(?!=)/g)) add(L(m.index), id('js-10', 'ts-11'), `${m[0]} instead of ${m[0] === '==' ? '===' : '!=='}`);
  for (const m of withStrings.matchAll(/\.removeAttribute\(\s*['"]data-[\w-]+['"]|\.setAttribute\(\s*['"]data-[\w-]+['"]\s*,\s*(?:''|"")\s*\)/g)) add(L(m.index), id('js-11', 'ts-16'), 'state attribute removed or set empty');
  for (const m of code.matchAll(/\.classList\s*\.\s*(add|remove|toggle)\s*\(/g)) add(L(m.index), id('js-11-class', 'ts-16-class'), `classList.${m[1]}`);
  const listeners = [...code.matchAll(/\baddEventListener\s*\(/g)];
  if (listeners.length && !/\bremoveEventListener\b|\bAbortController\b|\bsignal\b|\bonce\s*:\s*true/.test(code)) {
    add(L(listeners[0].index), id('js-04', 'ts-05'), `${listeners.length} addEventListener, no removeEventListener or abort signal`);
  }
  const lines = text.split('\n');
  lines.forEach((l, i) => {
    if (/^\s*\/\/\s*(?:[\w$.[\]]+\s*\(.*\)|(?:const|let|var|function|class|import|export|return|if|for|while)\b.*|[\w$.[\]]+\s*[+\-*/]?=[^=].*)\s*[;{}]\s*$/.test(l) && !/eslint|prettier|@ts-/.test(l)) add(i + 1, id('js-08', 'ts-09'), 'commented-out code');
  });
  if (ts) {
    for (const m of code.matchAll(/:\s*any\b|\bas\s+any\b|<any>|\bany\[\]/g)) add(L(m.index), 'ts-01', 'explicit any');
    for (const m of code.matchAll(/^\s*(?:export\s+)?(?:declare\s+)?type\s+[\w$]+\s*(?:<[^>]*>)?\s*=\s*\{(?!\s*(?:readonly\s+)?\[)/gm)) {
      const open = m.index + m[0].length - 1;
      const after = code.slice(matchBrace(code, open)).match(/^\s*(.)/);
      if (!after || (after[1] !== '|' && after[1] !== '&')) add(L(m.index + m[0].search(/\S/)), 'ts-12', 'object shape declared with type; use interface');
    }
    for (const m of code.matchAll(/\benum\s+([a-z_$][\w$]*)/g)) add(L(m.index), 'ts-13', `enum ${m[1]} must be PascalCase`);
    code.split('\n').forEach((l, i) => {
      if (/^\s*(import|export\s*(\{|\*))/.test(l)) return;
      if (/\bas\s+(?:[A-Z][\w$.]*|string\b|number\b|boolean\b|unknown\b|any\b|never\b|object\b|bigint\b|symbol\b|null\b|undefined\b|\{|\()/.test(l) && !/\/\/\s*\S/.test(lines[i])) add(i + 1, 'ts-15', 'type assertion without a justifying comment');
    });
  }
  return out;
}

// Findings for one file's text. profile "edit" keeps the small set edit-check has always run per edit.
function checkText(rel, text, cfg = {}, profile = 'audit') {
  let f = [];
  if (CSS_EXT.test(rel)) f.push(...cssChecks(rel, text));
  if (MARKUP_EXT.test(rel)) {
    f.push(...markupChecks(rel, text));
    if (PAGE_EXT.test(rel)) f.push(...pageChecks(rel, text));
  }
  if (SCRIPT_EXT.test(rel)) f.push(...scriptChecks(rel, text));
  if (profile === 'edit') {
    f = f.filter((x) => (RULES[x.rule] && RULES[x.rule].edit) || (x.rule === 'css-style-block' && cfg.styleBlocks === 'forbid'));
    f = f.map((x) => (x.rule === 'css-style-block' ? { ...x, msg: '<style> block is forbidden by this project' } : x));
  }
  const skip = new Set(cfg.skipRules || []);
  return f.filter((x) => !skip.has(x.rule)).sort((a, b) => a.line - b.line);
}

// ---- repository-level packs ----
function gitChecks(cwd, cfg) {
  const out = [];
  const inside = run('git', ['rev-parse', '--is-inside-work-tree'], cwd, 5000);
  if (inside.status !== 0) return out;
  const add = (file, rule, msg, detail) => out.push({ file, line: 0, rule, msg, detail });
  const TYPES = 'feat|fix|patch|style|refactor|chore|docs|test|remove';
  const log = run('git', ['log', '-n', String(cfg.commits || 200), '--no-merges', '--format=%h%x09%s'], cwd);
  for (const row of (log.stdout || '').split('\n').filter(Boolean)) {
    const [sha, ...rest] = row.split('\t');
    const subject = rest.join('\t');
    if (/^(Merge|Revert) /.test(subject)) continue;
    const m = new RegExp(`^(${TYPES})(\\([^)]+\\))?!?: (.+)$`).exec(subject);
    if (!m) { add(`commit:${sha}`, 'g-06', 'not "[type]: [summary]"', subject); continue; }
    const s = m[3];
    // the 50-character limit is on the whole header line (type, scope and summary), as in the 50/72 convention
    if (subject.length > 50) add(`commit:${sha}`, 'g-08', `header is ${subject.length} characters (limit 50)`, subject);
    else if (/\.$/.test(s)) add(`commit:${sha}`, 'g-08', 'summary ends with a period', subject);
    else if (/^(added|updated|fixed|removed|changed|adds|fixes|updates|removes|changes)\b/i.test(s)) add(`commit:${sha}`, 'g-08', 'summary not imperative present tense', subject);
  }
  const br = run('git', ['branch', '-a', '--format=%(refname:short)'], cwd);
  const seen = new Set();
  for (const raw of (br.stdout || '').split('\n').map((x) => x.trim()).filter(Boolean)) {
    const name = raw.replace(/^(origin|upstream)\//, '');
    // main, beta, test and dev are the standard's permanent branches (git-standards); master and develop are common aliases
    if (seen.has(name) || /^(HEAD|main|master|beta|test|dev|develop|origin|upstream)$/.test(name) || /^HEAD /.test(name) || /^\(/.test(name)) continue;
    seen.add(name);
    if (!/^(feature|fix|experiment|refactor|chore|docs)\/[\w.-]+/.test(name)) add(`branch:${name}`, 'g-05', 'branch name is not [type]/[short-description]', name);
  }
  return out;
}

function versionChecks(cwd, inGit) {
  const out = [];
  let pkg;
  try { pkg = JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf8')); } catch { return out; }
  const ver = pkg.version;
  if (typeof ver !== 'string' || pkg.private === true) return out; // the V rules govern released packages; a private app is never published
  const add = (rule, msg) => out.push({ file: 'package.json', line: 0, rule, msg, detail: msg });
  if (/-/.test(ver) && !/^\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/.test(ver)) add('v-09', `version ${ver} uses a non-standard pre-release suffix`);
  const clog = fs.readdirSync(cwd).find((f) => /^changelog\.md$/i.test(f));
  if (!clog) add('v-08', 'no CHANGELOG.md');
  else {
    const esc = ver.replace(/[.+^${}()|[\]\\]/g, '\\$&');
    if (!new RegExp(`^##\\s*\\[?v?${esc}\\]?`, 'm').test(fs.readFileSync(path.join(cwd, clog), 'utf8'))) add('v-08', `CHANGELOG.md has no entry for ${ver}`);
  }
  if (inGit) {
    const tag = run('git', ['describe', '--tags', '--abbrev=0'], cwd, 5000);
    const t = (tag.stdout || '').trim().replace(/^v/, '');
    if (tag.status === 0 && t && t !== ver) add('v-05', `package.json ${ver} vs latest tag ${t}`);
  }
  return out;
}

// ---- audit driver ----
function listFiles(cwd) {
  const g = run('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], cwd);
  if (g.status === 0 && g.stdout) return g.stdout.split('\0').filter(Boolean).map(norm);
  const out = [];
  (function walk(d) {
    let ents = [];
    try { ents = fs.readdirSync(path.join(cwd, d), { withFileTypes: true }); } catch { return; }
    for (const e of ents) {
      const r = d ? d + '/' + e.name : e.name;
      if (e.isDirectory()) { if (!SKIP_DIRS.test(r + '/')) walk(r); } else out.push(r);
    }
  })('');
  return out;
}

function audit(cwd, cfg = {}, opt = {}) {
  const findings = [];
  let scanned = 0, generated = 0;
  const skipped = [];
  const markSkipped = (rel) => { generated++; skipped.push(rel); };
  const only = (opt.paths || []).map((p) => norm(p).replace(/^\.\//, '').replace(/\/$/, ''));
  const ignores = [...(cfg.ignore || []), ...(opt.ignore || [])].map(globRe);
  const stds = opt.standard ? new Set(opt.standard) : null;
  for (const rel of listFiles(cwd)) {
    if (!CSS_EXT.test(rel) && !MARKUP_EXT.test(rel) && !SCRIPT_EXT.test(rel)) continue;
    if (only.length && !only.some((p) => rel === p || rel.startsWith(p + '/'))) continue;
    if (SKIP_DIRS.test(rel) || ignores.some((re) => re.test(rel))) continue;
    if (!opt.includeGenerated && GENERATED_NAME.test(path.basename(rel))) { markSkipped(rel); continue; }
    let text;
    try { const abs = path.join(cwd, rel); if (fs.statSync(abs).size > 2 * 1024 * 1024) { markSkipped(rel); continue; } text = fs.readFileSync(abs, 'utf8'); } catch { continue; }
    if (!opt.includeGenerated && (GENERATED.test(text.slice(0, 600)) || text.length / text.split('\n').length > 250)) { markSkipped(rel); continue; } // generated header, or bundled into very long lines
    scanned++;
    findings.push(...checkText(rel, text, cfg, 'audit'));
  }
  let inGit = false;
  if (!opt.noGit && !only.length) {
    const g = gitChecks(cwd, cfg);
    inGit = run('git', ['rev-parse', '--is-inside-work-tree'], cwd, 5000).status === 0;
    findings.push(...g, ...versionChecks(cwd, inGit));
  }
  const skip = new Set(cfg.skipRules || []);
  const kept = findings.filter((f) => !skip.has(f.rule) && (!stds || stds.has(RULES[f.rule].std)));
  return { scanned, generated, skipped, findings: kept };
}

function tally(findings) {
  const t = {}; // rule -> file -> [lines]
  for (const f of findings) ((t[f.rule] ||= {})[f.file] ||= []).push(f.line);
  return t;
}
const total = (byFile) => Object.values(byFile).reduce((n, l) => n + l.length, 0);
const KIND_ORDER = { rule: 0, review: 1, info: 2 };

// Directory names that usually hold code the project did not write; a hint is only given for those.
const VENDORISH = /^(vendors?|third[-_]?party|external|libs?|examples?|docs?|demos?|packages|three(\.js)?|jquery|bootstrap|public)$/i;
function vendorHint(findings) {
  const by = {};
  let all = 0;
  for (const f of findings) {
    if (f.line === 0) continue;
    all++;
    const seg = f.file.split('/');
    const i = seg.findIndex((x, k) => k < seg.length - 1 && VENDORISH.test(x));
    if (i >= 0) { const d = seg.slice(0, i + 1).join('/'); by[d] = (by[d] || 0) + 1; }
  }
  const [dir, n] = Object.entries(by).sort((a, b) => b[1] - a[1])[0] || [];
  return dir && n >= 50 && n / all >= 0.3 ? `hint: ${Math.round((100 * n) / all)}% of findings are under ${dir}/. If that is third-party or generated, rerun with --ignore '${dir}/**' (or add it to ignore in .claude/code-audit.json).` : null;
}

function report(res, base, opt, cwd) {
  const t = tally(res.findings);
  const rules = Object.keys(t).sort((a, b) => KIND_ORDER[RULES[a].kind] - KIND_ORDER[RULES[b].kind] || total(t[b]) - total(t[a]));
  const fileCount = new Set(res.findings.filter((f) => f.line !== 0).map((f) => f.file)).size;
  const out = [`audit: ${res.scanned} files scanned${res.generated ? ` (${res.generated} generated/minified skipped)` : ''}, ${res.findings.length} findings in ${fileCount} files`];
  const regressed = [];
  if (base) {
    for (const r of rules) for (const [file, lines] of Object.entries(t[r])) {
      const before = (base.rules[r] || {})[file] || 0;
      if (lines.length > before) regressed.push(`${r} ${file} ${before} -> ${lines.length}`);
    }
    const was = Object.values(base.rules).reduce((n, byFile) => n + Object.values(byFile).reduce((m, c) => m + c, 0), 0);
    out[0] += `  (baseline ${base.date}: ${was} -> ${res.findings.length}, ${res.findings.length - was >= 0 ? '+' : ''}${res.findings.length - was})`;
  }
  if (opt.showSkipped) {
    out.push(`skipped (${res.skipped.length}): generated header, generated or minified name, or bundled into very long lines; rerun with --include-generated to audit them`);
    out.push(...res.skipped.map((x) => '  ' + x));
    return out.join('\n');
  }
  if (opt.rule) {
    const byFile = t[opt.rule] || {};
    const cache = {};
    const src = (file, line) => {
      if (!opt.context || !line) return '';
      try { cache[file] ||= fs.readFileSync(path.join(cwd, file), 'utf8').split('\n'); return '  ' + (cache[file][line - 1] || '').trim().slice(0, 100); } catch { return ''; }
    };
    const f = res.findings.filter((x) => x.rule === opt.rule);
    const lines = f.map((x) => `${x.file}${x.line ? ':' + x.line : ''}${x.detail ? '  ' + x.detail : ''}${src(x.file, x.line)}`);
    out.push(`${opt.rule} [${(RULES[opt.rule] || {}).kind}]: ${lines.length} occurrences in ${Object.keys(byFile).length} files (${(RULES[opt.rule] || {}).what || 'unknown rule'})`);
    out.push(...lines.slice(0, opt.limit));
    if (lines.length > opt.limit) out.push(`(+${lines.length - opt.limit} more; raise --limit)`);
    return out.join('\n');
  }
  if (!rules.length) return out.join('\n');
  out.push('rule             kind    count  files  what');
  for (const r of rules) out.push(`${r.padEnd(16)} ${RULES[r].kind.padEnd(7)} ${String(total(t[r])).padStart(5)} ${String(Object.keys(t[r]).length).padStart(6)}  ${RULES[r].what}`);
  const hint = vendorHint(res.findings);
  if (hint) out.push(hint);
  for (const r of rules.filter((x) => RULES[x].kind === 'rule' && Object.values(t[x]).some((l) => l[0] !== 0)).slice(0, opt.sections)) {
    const worst = Object.entries(t[r]).sort((a, b) => b[1].length - a[1].length).slice(0, opt.top);
    out.push(`${r} worst files:`);
    for (const [file, ls] of worst) out.push(`  ${file} ${ls.length} (L${ls.slice(0, 6).join(',L')}${ls.length > 6 ? ',...' : ''})`);
  }
  if (regressed.length) {
    out.push(`regressed since baseline (${regressed.length}):`);
    out.push(...regressed.slice(0, 10).map((x) => '  ' + x));
    if (regressed.length > 10) out.push(`  (+${regressed.length - 10} more)`);
  }
  out.push('next: --rule <id> lists every file:line (add --context for the source line); --baseline saves these counts; --list shows every rule checked.');
  return out.join('\n');
}

function listRules() {
  const rows = Object.values(RULES).map((r) => `${r.id.padEnd(16)} ${r.std.padEnd(8)} ${r.kind.padEnd(7)} ${r.edit ? 'edit ' : '     '} ${r.what}`);
  return ['rule             standard kind    per-edit what', ...rows, '', NOT_CHECKED].join('\n');
}

function main() {
  const a = process.argv.slice(2);
  let cwd = process.cwd();
  let json = false, list = false;
  const opt = { rule: null, top: 5, sections: 6, limit: 200, baseline: false, context: false, noGit: false, ignore: [], paths: [], standard: null };
  for (let i = 0; i < a.length; i++) {
    const v = a[i];
    if (v === '--cwd') cwd = path.resolve(a[++i]);
    else if (v === '--json') json = true;
    else if (v === '--list') list = true;
    else if (v === '--baseline') opt.baseline = true;
    else if (v === '--context') opt.context = true;
    else if (v === '--no-git') opt.noGit = true;
    else if (v === '--include-generated') opt.includeGenerated = true;
    else if (v === '--skipped') opt.showSkipped = true;
    else if (v === '--rule') opt.rule = a[++i];
    else if (v === '--standard') opt.standard = String(a[++i]).split(',').map((s) => s.trim()).filter(Boolean);
    else if (v === '--ignore') opt.ignore.push(a[++i]);
    else if (v === '--top') opt.top = Math.max(1, Number(a[++i]) || 5);
    else if (v === '--limit') opt.limit = Math.max(1, Number(a[++i]) || 200);
    else if (v === '--commits') opt.commits = Math.max(1, Number(a[++i]) || 200);
    else if (v === '--sections') opt.sections = Math.max(1, Number(a[++i]) || 6);
    else if (v === '--audit') continue; // accepted so the old edit-check spelling still works
    else if (v.startsWith('--')) { console.log(`unknown option ${v}; see the header of this file`); process.exitCode = 2; return; }
    else opt.paths.push(v);
  }
  if (list) { console.log(listRules()); return; }
  let cfg = {};
  try { cfg = JSON.parse(fs.readFileSync(path.join(cwd, '.claude', 'code-audit.json'), 'utf8')); } catch { /* defaults */ }
  if (opt.commits) cfg.commits = opt.commits;
  if (opt.rule && !RULES[opt.rule]) { console.log(`unknown rule ${opt.rule}; run --list`); process.exitCode = 2; return; }
  const res = audit(cwd, cfg, opt);
  let base = null;
  try { base = JSON.parse(fs.readFileSync(path.join(cwd, BASELINE), 'utf8')); } catch { /* no baseline yet */ }
  const t = tally(res.findings);
  if (opt.baseline) {
    const rules = Object.fromEntries(Object.entries(t).map(([r, byFile]) => [r, Object.fromEntries(Object.entries(byFile).map(([f, l]) => [f, l.length]))]));
    fs.mkdirSync(path.join(cwd, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(cwd, BASELINE), JSON.stringify({ date: new Date().toISOString().slice(0, 10), rules }, null, 1));
  }
  if (json) console.log(JSON.stringify(res, null, 2));
  else console.log(report(res, opt.baseline ? null : base, opt, cwd) + (opt.baseline ? `\nbaseline saved to ${norm(BASELINE)}` : ''));
  // exit 1 only when counts rose against a saved baseline, so it can gate CI without failing on old debt
  if (base && !opt.baseline) {
    process.exitCode = Object.entries(t).some(([r, byFile]) => Object.entries(byFile).some(([f, l]) => l.length > ((base.rules[r] || {})[f] || 0))) ? 1 : 0;
  }
}

if (require.main === module) main();
module.exports = { checkText, audit, report, listRules, stripCode, RULES };
